### ISSUE TITLE
Unstable Assembly test is failing due to divergent branch history during test

### ISSUE THREAD

**Issue by alexdunnjpl** [NASA-PDS/registry-api#534]
### 💡 Description

I'm not sure how this is even possible

```
DEBUG:pds.roundup.util:🏃‍♀️ Running «['git', 'pull', 'origin', 'main']»

CRITICAL:pds.roundup.util:💥 Process with command line ['git', 'pull', 'origin', 'main'] failed with status 128

CRITICAL:pds.roundup.util:🪵 Stdout = «»

CRITICAL:pds.roundup.util:📚 Stderr = «From https://github.com/NASA-PDS/registry-api

* branch main -> FETCH_HEAD

hint: You have divergent branches and need to specify how to reconcile them.

hint: You can do so by running one of the following commands sometime before

hint: your next pull:

hint:

hint: git config pull.rebase false # merge

hint: git config pull.rebase true # rebase

hint: git config pull.ff only # fast-forward only

hint:

hint: You can replace "git config" with "git config --global" to set a default

hint: preference for all repositories. You can also pass --rebase, --no-rebase,

hint: or --ff-only on the command line to override the configured default per

hint: invocation.

fatal: Need to specify how to reconcile divergent branches.

»

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 62, in invoke

cp = subprocess.run(argv, stdin=subprocess.DEVNULL, capture_output=True, check=True)

File "/usr/local/lib/python3.9/subprocess.py", line 528, in run

raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '['git', 'pull', 'origin', 'main']' returned non-zero exit status 128.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

File "/usr/local/bin/roundup", line 8, in <module>

sys.exit(main())

File "/usr/local/lib/python3.9/site-packages/pds/roundup/main.py", line 119, in main

_assemblies[args.assembly](context).roundup()

File "/usr/local/lib/python3.9/site-packages/pds/roundup/assembly.py", line 42, in roundup

step.execute()

File "/usr/local/lib/python3.9/site-packages/pds/roundup/step.py", line 154, in execute

git_pull()

File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 119, in git_pull

invokeGIT(['pull', 'origin', 'main'])

File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 101, in invokeGIT

return invoke(argv)

File "/usr/local/lib/python3.9/site-packages/pds/roundup/util.py", line 71, in invoke

raise InvokedProcessError(ex)

pds.roundup.errors.InvokedProcessError: ('Process %s failed with code %d', ['git', 'pull', 'origin', 'main'], 128)
```

**Comment by alexdunnjpl** [comment]
This _appears_ (best-effort) to be the first occurrence of this issue, but the commit contents appears unrelated to the issue itself.

https://github.com/NASA-PDS/registry-api/actions/runs/10191056665/job/28191735622

**Comment by alexdunnjpl** [comment]
Per @jordanpadams 

> because unstable sometimes pushes things to main, so if it was updated after the build was triggered, it will fail
>
> if not, you may just need to update the unstable build  to include `workflow_dispatch:`

**Comment by jordanpadams** [comment]
I think this is outdated and now invalid
